### ISSUE TITLE
ASGITestClient doesn't send websocket close code on disconnect

### ISSUE THREAD

**Issue by villekr** [klen/asgi-tools#7]
ASGITestClient doesn't send websocket close code, which is mandatory value in ASGI specification. Currently only "type" is send.
https://asgi.readthedocs.io/en/latest/specs/www.html#disconnect-receive-event-ws

```python
    async def disconnect(self):
        await self.send({'type': 'websocket.disconnect'})
        self.state = self.STATES.disconnected
```

WebSocket error codes:
https://datatracker.ietf.org/doc/html/rfc6455#section-7.4

**Comment by klen** [comment]
@villekr Thank you 🙏. The client has been updated (`asgi-tools 0.61.5`).

**Comment by villekr** [comment]
Works now. Thanks for quick fix!
